services:
  backend:
    build: ./backend
    container_name: harmonic-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: harmonic-frontend
    ports:
      - "5174:5174"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend